spring.application.name=crm
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
spring.jackson.serialization.write-dates-as-timestamps=false

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=${JWT_SECRET:Y2xhdmVfcG9jaGlfbW92aWxfc2VjcmV0XzI1Nl9iaXRzX3NlZ3VyYQ==}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ===============================
# DATABASE
# ===============================
# URL de conexión a la base de datos PostgreSQL con SSL requerido para mayor seguridad
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://136.119.241.217:5432/dental_db?sslmode=require}
# Usuario de la base de datos
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# Contraseña de la base de datos
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Cotemar19$}

# Estrategia de generación de tablas: 'update' sincroniza el esquema de la DB con las entidades JPA
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
# Habilita la impresión de las consultas SQL en la consola para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=update
server.port=${PORT:8084}

# Configuración de Firebase
firebase.config.path=${FIREBASE_CONFIG_PATH:classpath:firebase-config.json}

whatsapp.verify-token=${WHATSAPP_VERIFY_TOKEN:mi_token_secreto_2026}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN:default_token}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID:default_id}
whatsapp.api-url=${WHATSAPP_API_URL:https://graph.facebook.com/v22.0}


# OpenAI Configuration
openai.api.key=${OPENAI_API_KEY:default_key}
openai.model=${OPENAI_MODEL:gpt-4o-mini}
openai.max-tokens=250
openai.temperature=0.7
openai.max-retries=3
openai.retry-delay=1000


# R2 Configuration
cloudflare.r2.endpoint=${R2_ENDPOINT:https://default-endpoint.com}
cloudflare.r2.access-key-id=${R2_ACCESS_KEY:default-key}
cloudflare.r2.secret-access-key=${R2_SECRET_KEY:default-secret}
cloudflare.r2.bucket-name=${R2_BUCKET:meyi-imagenes}
cloudflare.r2.public-url=${R2_PUBLIC_URL:https://pub-8c6866b9de504c61a0aa8938f5cdc44c.r2.dev}

# ===============================
# EMAIL CONFIG (GMAIL)
# ===============================
# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:tu_correo@gmail.com}
spring.mail.password=${MAIL_PASSWORD:tu_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000